[relaychain]
default_command = "polkadot"
chain = "rococo-local"

[[relaychain.nodes]]
name = "alice"
validator = true
rpc_port = 9944

[[relaychain.nodes]]
name = "bob"
validator = true
rpc_port = 9955

[[parachains]]
id = 2000
default_command = "./target/debug/dumb-pokemon-node"

[[parachains.collators]]
name = "charlie"
rpc_port = 9988

